package ttt;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.ImageIcon;

/**
 *
 * @author Dahle
 */
public class TTT extends javax.swing.JFrame implements KeyListener {

    private CreateDialogue createDialogue;
    private ConnectDialogue connectDialogue;
    private ImageIcon ring;
    private ImageIcon cross;
    private ImageIcon sRing;
    private ImageIcon sCross;
    private TTTLogic logic;
    private int newChatMessages;
    private int newSystemMessages;
    private ImageIcon playerIcon;
    private ImageIcon sPlayerIcon;
    private ImageIcon opponentIcon;

    /**
     * Creates new form TTT
     */
    public TTT() {
        initComponents();
        this.setLocationRelativeTo(null);
        ring = new javax.swing.ImageIcon(getClass().getResource("/ttt/ring.png"));
        cross = new javax.swing.ImageIcon(getClass().getResource("/ttt/cross.png"));
        sRing = new javax.swing.ImageIcon(getClass().getResource("/ttt/sRing.png"));
        sCross = new javax.swing.ImageIcon(getClass().getResource("/ttt/sCross.png"));
        jTextFieldChat.addKeyListener(this);
        logic = new TTTLogic(this);
        this.setTitle("Tic Tac Toe");
        newChatMessages = 0;
        newSystemMessages = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanelField = new javax.swing.JPanel();
        jButton_x1y3 = new javax.swing.JButton();
        jButton_x2y3 = new javax.swing.JButton();
        jButton_x1y2 = new javax.swing.JButton();
        jButton_x2y2 = new javax.swing.JButton();
        jButton_x3y3 = new javax.swing.JButton();
        jButton_x3y2 = new javax.swing.JButton();
        jButton_x1y1 = new javax.swing.JButton();
        jButton_x3y1 = new javax.swing.JButton();
        jButton_x2y1 = new javax.swing.JButton();
        jButtonDone = new javax.swing.JButton();
        jPanelBank = new javax.swing.JPanel();
        jLabelBank2 = new javax.swing.JLabel();
        jLabelBank3 = new javax.swing.JLabel();
        jLabelBank1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaChat = new javax.swing.JTextArea();
        jBtnSend = new javax.swing.JButton();
        jTextFieldChat = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaSystem = new javax.swing.JTextArea();
        jPanel_x1y2 = new javax.swing.JPanel();
        jLabel_x1y3 = new javax.swing.JLabel();
        jLabel_x1y2 = new javax.swing.JLabel();
        jLabel_x1y1 = new javax.swing.JLabel();
        jLabel_x3y3 = new javax.swing.JLabel();
        jLabel_x2y3 = new javax.swing.JLabel();
        jLabel_x3y2 = new javax.swing.JLabel();
        jLabel_x2y2 = new javax.swing.JLabel();
        jLabel_x3y1 = new javax.swing.JLabel();
        jLabel_x2y1 = new javax.swing.JLabel();
        jLabelPlayerNumber = new javax.swing.JLabel();
        jLabelMoveTo = new javax.swing.JLabel();
        jLabelMoveFrom = new javax.swing.JLabel();
        jButtonUpdate = new javax.swing.JButton();
        jLabelBank = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemConnect = new javax.swing.JMenuItem();
        jMenuItemCreate = new javax.swing.JMenuItem();
        jMenuItemQuit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanelField.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton_x1y3.setMaximumSize(new java.awt.Dimension(73, 73));
        jButton_x1y3.setMinimumSize(new java.awt.Dimension(73, 73));
        jButton_x1y3.setName("x1y3"); // NOI18N
        jButton_x1y3.setPreferredSize(new java.awt.Dimension(73, 73));
        jButton_x1y3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_x1y3ActionPerformed(evt);
            }
        });

        jButton_x2y3.setMaximumSize(new java.awt.Dimension(73, 73));
        jButton_x2y3.setMinimumSize(new java.awt.Dimension(73, 73));
        jButton_x2y3.setName("x2y3"); // NOI18N
        jButton_x2y3.setPreferredSize(new java.awt.Dimension(73, 73));
        jButton_x2y3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_x2y3ActionPerformed(evt);
            }
        });

        jButton_x1y2.setMaximumSize(new java.awt.Dimension(73, 73));
        jButton_x1y2.setMinimumSize(new java.awt.Dimension(73, 73));
        jButton_x1y2.setName("x1y2"); // NOI18N
        jButton_x1y2.setPreferredSize(new java.awt.Dimension(73, 73));
        jButton_x1y2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_x1y2ActionPerformed(evt);
            }
        });

        jButton_x2y2.setMaximumSize(new java.awt.Dimension(73, 73));
        jButton_x2y2.setMinimumSize(new java.awt.Dimension(73, 73));
        jButton_x2y2.setName("x2y2"); // NOI18N
        jButton_x2y2.setPreferredSize(new java.awt.Dimension(73, 73));
        jButton_x2y2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_x2y2ActionPerformed(evt);
            }
        });

        jButton_x3y3.setMaximumSize(new java.awt.Dimension(73, 73));
        jButton_x3y3.setMinimumSize(new java.awt.Dimension(73, 73));
        jButton_x3y3.setName("x3y3"); // NOI18N
        jButton_x3y3.setPreferredSize(new java.awt.Dimension(73, 73));
        jButton_x3y3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_x3y3ActionPerformed(evt);
            }
        });

        jButton_x3y2.setMaximumSize(new java.awt.Dimension(73, 73));
        jButton_x3y2.setMinimumSize(new java.awt.Dimension(73, 73));
        jButton_x3y2.setName("x3y2"); // NOI18N
        jButton_x3y2.setPreferredSize(new java.awt.Dimension(73, 73));
        jButton_x3y2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_x3y2ActionPerformed(evt);
            }
        });

        jButton_x1y1.setMaximumSize(new java.awt.Dimension(73, 73));
        jButton_x1y1.setMinimumSize(new java.awt.Dimension(73, 73));
        jButton_x1y1.setName("x1y1"); // NOI18N
        jButton_x1y1.setPreferredSize(new java.awt.Dimension(73, 73));
        jButton_x1y1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_x1y1ActionPerformed(evt);
            }
        });

        jButton_x3y1.setMaximumSize(new java.awt.Dimension(73, 73));
        jButton_x3y1.setMinimumSize(new java.awt.Dimension(73, 73));
        jButton_x3y1.setName("x3y1"); // NOI18N
        jButton_x3y1.setPreferredSize(new java.awt.Dimension(73, 73));
        jButton_x3y1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_x3y1ActionPerformed(evt);
            }
        });

        jButton_x2y1.setMaximumSize(new java.awt.Dimension(73, 73));
        jButton_x2y1.setMinimumSize(new java.awt.Dimension(73, 73));
        jButton_x2y1.setName("x2y1"); // NOI18N
        jButton_x2y1.setPreferredSize(new java.awt.Dimension(73, 73));
        jButton_x2y1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_x2y1ActionPerformed(evt);
            }
        });

        jButtonDone.setText("Done");
        jButtonDone.setMaximumSize(new java.awt.Dimension(73, 23));
        jButtonDone.setMinimumSize(new java.awt.Dimension(73, 23));
        jButtonDone.setPreferredSize(new java.awt.Dimension(73, 23));
        jButtonDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoneActionPerformed(evt);
            }
        });

        jLabelBank2.setMaximumSize(new java.awt.Dimension(23, 23));
        jLabelBank2.setMinimumSize(new java.awt.Dimension(23, 23));
        jLabelBank2.setPreferredSize(new java.awt.Dimension(23, 23));

        jLabelBank3.setMaximumSize(new java.awt.Dimension(23, 23));
        jLabelBank3.setMinimumSize(new java.awt.Dimension(23, 23));
        jLabelBank3.setPreferredSize(new java.awt.Dimension(23, 23));

        jLabelBank1.setMaximumSize(new java.awt.Dimension(23, 23));
        jLabelBank1.setMinimumSize(new java.awt.Dimension(23, 23));
        jLabelBank1.setPreferredSize(new java.awt.Dimension(23, 23));

        javax.swing.GroupLayout jPanelBankLayout = new javax.swing.GroupLayout(jPanelBank);
        jPanelBank.setLayout(jPanelBankLayout);
        jPanelBankLayout.setHorizontalGroup(
            jPanelBankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBankLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBank1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelBank2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelBank3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanelBankLayout.setVerticalGroup(
            jPanelBankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBank2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabelBank3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabelBank1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanelFieldLayout = new javax.swing.GroupLayout(jPanelField);
        jPanelField.setLayout(jPanelFieldLayout);
        jPanelFieldLayout.setHorizontalGroup(
            jPanelFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFieldLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFieldLayout.createSequentialGroup()
                        .addGroup(jPanelFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelFieldLayout.createSequentialGroup()
                                .addComponent(jButton_x1y1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_x2y1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanelBank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton_x3y1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDone, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelFieldLayout.createSequentialGroup()
                        .addComponent(jButton_x1y3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_x2y3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_x3y3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelFieldLayout.createSequentialGroup()
                        .addComponent(jButton_x1y2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_x2y2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_x3y2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelFieldLayout.setVerticalGroup(
            jPanelFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFieldLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_x2y3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_x1y3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_x3y3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_x1y2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_x2y2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_x3y2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_x2y1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_x1y1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_x3y1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonDone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelBank, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jTextAreaChat.setColumns(20);
        jTextAreaChat.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jTextAreaChat.setLineWrap(true);
        jTextAreaChat.setRows(5);
        jTextAreaChat.setWrapStyleWord(true);
        jTextAreaChat.setEnabled(false);
        jScrollPane1.setViewportView(jTextAreaChat);

        jBtnSend.setText("Send");
        jBtnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextFieldChat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnSend)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnSend)
                    .addComponent(jTextFieldChat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Chat", jPanel2);

        jTextAreaSystem.setColumns(20);
        jTextAreaSystem.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jTextAreaSystem.setRows(5);
        jTextAreaSystem.setEnabled(false);
        jScrollPane2.setViewportView(jTextAreaSystem);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("System", jPanel5);

        jPanel_x1y2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel_x1y3.setText("X");

        jLabel_x1y2.setText("X");

        jLabel_x1y1.setText("X");

        jLabel_x3y3.setText("X");

        jLabel_x2y3.setText("X");

        jLabel_x3y2.setText("X");

        jLabel_x2y2.setText("X");

        jLabel_x3y1.setText("X");

        jLabel_x2y1.setText("X");

        jLabelPlayerNumber.setText("Player nr:");

        jLabelMoveTo.setText("MoveFrom: ");

        jLabelMoveFrom.setText("MoveTo:");

        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jLabelBank.setText("Bank nr:");

        javax.swing.GroupLayout jPanel_x1y2Layout = new javax.swing.GroupLayout(jPanel_x1y2);
        jPanel_x1y2.setLayout(jPanel_x1y2Layout);
        jPanel_x1y2Layout.setHorizontalGroup(
            jPanel_x1y2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_x1y2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_x1y2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_x1y2Layout.createSequentialGroup()
                        .addComponent(jLabel_x1y3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_x2y3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_x3y3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelMoveTo))
                    .addGroup(jPanel_x1y2Layout.createSequentialGroup()
                        .addComponent(jLabel_x1y2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_x2y2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_x3y2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelMoveFrom))
                    .addGroup(jPanel_x1y2Layout.createSequentialGroup()
                        .addComponent(jLabel_x1y1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_x2y1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_x3y1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelBank))
                    .addGroup(jPanel_x1y2Layout.createSequentialGroup()
                        .addComponent(jLabelPlayerNumber)
                        .addGap(168, 168, 168)
                        .addComponent(jButtonUpdate)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_x1y2Layout.setVerticalGroup(
            jPanel_x1y2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_x1y2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_x1y2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonUpdate)
                    .addGroup(jPanel_x1y2Layout.createSequentialGroup()
                        .addGroup(jPanel_x1y2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_x1y3)
                            .addComponent(jLabel_x2y3)
                            .addComponent(jLabel_x3y3)
                            .addComponent(jLabelMoveTo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_x1y2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_x1y2)
                            .addComponent(jLabel_x2y2)
                            .addComponent(jLabel_x3y2)
                            .addComponent(jLabelMoveFrom))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_x1y2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_x1y1)
                            .addComponent(jLabel_x2y1)
                            .addComponent(jLabel_x3y1)
                            .addComponent(jLabelBank))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPlayerNumber)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        jMenuItemConnect.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemConnect.setText("Connect to game");
        jMenuItemConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConnectActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemConnect);

        jMenuItemCreate.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemCreate.setText("Create Game");
        jMenuItemCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCreateActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCreate);

        jMenuItemQuit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemQuit.setText("Quit");
        jMenuItemQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemQuitActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemQuit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem1.setText("Disconnect");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Development");

        jMenuItem2.setText("jMenuItem2");
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_x1y2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_x1y2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCreateActionPerformed
        createDialogue = new CreateDialogue(this, true);
        createDialogue.setLocationRelativeTo(this);
        createDialogue.setVisible(true);
        if (createDialogue.ok()) {
            int port;
            port = createDialogue.getPort();
            String ipAddress;
            ipAddress = createDialogue.getIpAddress();
            createDialogue.dispose();
            logic.listen(ipAddress, port);
        }
    }//GEN-LAST:event_jMenuItemCreateActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        logic = null;
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton_x1y3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_x1y3ActionPerformed

    }//GEN-LAST:event_jButton_x1y3ActionPerformed

    private void jButton_x2y3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_x2y3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_x2y3ActionPerformed

    private void jButton_x1y2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_x1y2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_x1y2ActionPerformed

    private void jButton_x2y2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_x2y2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_x2y2ActionPerformed

    private void jButton_x3y3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_x3y3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_x3y3ActionPerformed

    private void jButton_x3y2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_x3y2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_x3y2ActionPerformed

    private void jButton_x1y1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_x1y1ActionPerformed
        javax.swing.JButton btn = (javax.swing.JButton) evt.getSource();
        btn.setIcon(null);
        
    }//GEN-LAST:event_jButton_x1y1ActionPerformed

    private void jButton_x3y1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_x3y1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_x3y1ActionPerformed

    private void jButton_x2y1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_x2y1ActionPerformed
        javax.swing.JButton btn = (javax.swing.JButton) evt.getSource();
        /*if (logic.getPlayerBank() > 0){
            logic.setMoveFrom("x0y0");
            logic.setMoveTo(btn.getName());
            btn.setIcon(playerIcon);
            logic.setPlayerBank(logic.getPlayerBank() - 1);
        }else if(logic.getPlayerBank() == 0 && logic.getX2y1() == logic.getPlayer()){
            logic.setMoveFrom(btn.getName());
        }else if(!logic.getMoveFrom().equalsIgnoreCase("")){
            logic.setMoveTo(btn.getName());
            btn.setIcon(playerIcon);
        }*/
    }//GEN-LAST:event_jButton_x2y1ActionPerformed

    private void jBtnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSendActionPerformed
        sendChatMessage();
    }//GEN-LAST:event_jBtnSendActionPerformed

    private void jMenuItemConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConnectActionPerformed
        connectDialogue = new ConnectDialogue(this, true);
        connectDialogue.setLocationRelativeTo(this);
        int port;
        String ipAddress;
        connectDialogue.setVisible(true);
        if (connectDialogue.ok()) {
            ipAddress = connectDialogue.getIpadress();
            port = connectDialogue.getPort();
            System.out.println(ipAddress + " " + port);
            connectDialogue.dispose();
            //Cancel what happens
            logic.connect(ipAddress, port);
        }
    }//GEN-LAST:event_jMenuItemConnectActionPerformed

    private void jMenuItemQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemQuitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemQuitActionPerformed

    private void jButtonDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDoneActionPerformed
        if(!logic.getMoveFrom().equalsIgnoreCase("") && !logic.getMoveTo().equalsIgnoreCase(""));
        logic.sendMove();
        updateField();
    }//GEN-LAST:event_jButtonDoneActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        int selectedTab;
        selectedTab = jTabbedPane1.getSelectedIndex();
        if (selectedTab == 0) {
            jTabbedPane1.setTitleAt(0, "Chat");
            newChatMessages = 0;
        }
        if (selectedTab == 1) {
            jTabbedPane1.setTitleAt(1, "System");
            newSystemMessages = 0;
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        jLabel_x1y1.setText(Integer.toString(logic.getX1y1()));
        jLabel_x1y2.setText(Integer.toString(logic.getX1y2()));
        jLabel_x1y3.setText(Integer.toString(logic.getX1y3()));
        jLabel_x2y1.setText(Integer.toString(logic.getX2y1()));
        jLabel_x2y2.setText(Integer.toString(logic.getX2y2()));
        jLabel_x2y3.setText(Integer.toString(logic.getX2y3()));
        jLabel_x3y1.setText(Integer.toString(logic.getX3y1()));
        jLabel_x3y2.setText(Integer.toString(logic.getX3y2()));
        jLabel_x3y3.setText(Integer.toString(logic.getX3y3()));
        jLabelPlayerNumber.setText(Integer.toString(logic.getPlayer()));
        jLabelMoveTo.setText(logic.getMoveFrom());
        jLabelMoveFrom.setText(logic.getMoveTo());
        jLabelBank.setText(Integer.toString(logic.getBank()));
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TTT().setVisible(true);
            }
        });
    }

    public void appendChatMessage(String message) {
        jTextAreaChat.append(message + "\n");
        jTextAreaChat.setCaretPosition(jTextAreaChat.getDocument().getLength());
        newChatMessages++;
        if (jTabbedPane1.getSelectedIndex() != 0) {
            jTabbedPane1.setTitleAt(0, "Chat (" + newChatMessages + ")");
        }
    }

    public void appendSystemMessage(String message) {
        jTextAreaSystem.append(message + "\n");
        jTextAreaSystem.setCaretPosition(jTextAreaChat.getDocument().getLength());
        newSystemMessages++;
        if (jTabbedPane1.getSelectedIndex() != 1) {
            jTabbedPane1.setTitleAt(1, "System (" + newSystemMessages + ")");
        }
    }

    public void sendChatMessage() {
        if (!jTextFieldChat.getText().equalsIgnoreCase("")) {
            logic.sendChatMessage(jTextFieldChat.getText());
            System.out.println(jTextFieldChat.getText());
            jTextFieldChat.setText("");
        }
    }

    public void setRole(String role) {
        if (role.equalsIgnoreCase("server")) {
            this.setTitle(this.getTitle() + " - Server - Player " + logic.getPlayer());
            jMenuItemConnect.setEnabled(false);
            jMenuItemCreate.setEnabled(false);
            playerIcon = cross;
            sPlayerIcon = sCross;
            opponentIcon = ring;
        } else if (role.equalsIgnoreCase("client")) {
            this.setTitle(this.getTitle() + " - Client - Player " + logic.getPlayer());
            jMenuItemConnect.setEnabled(false);
            jMenuItemCreate.setEnabled(false);
            playerIcon = ring;
            sPlayerIcon = sRing;
            opponentIcon = cross;
        }
    }

    @Override
    public void keyPressed(KeyEvent e) {
        int key = e.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            sendChatMessage();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnSend;
    private javax.swing.JButton jButtonDone;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JButton jButton_x1y1;
    private javax.swing.JButton jButton_x1y2;
    private javax.swing.JButton jButton_x1y3;
    private javax.swing.JButton jButton_x2y1;
    private javax.swing.JButton jButton_x2y2;
    private javax.swing.JButton jButton_x2y3;
    private javax.swing.JButton jButton_x3y1;
    private javax.swing.JButton jButton_x3y2;
    private javax.swing.JButton jButton_x3y3;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabelBank;
    private javax.swing.JLabel jLabelBank1;
    private javax.swing.JLabel jLabelBank2;
    private javax.swing.JLabel jLabelBank3;
    private javax.swing.JLabel jLabelMoveFrom;
    private javax.swing.JLabel jLabelMoveTo;
    private javax.swing.JLabel jLabelPlayerNumber;
    private javax.swing.JLabel jLabel_x1y1;
    private javax.swing.JLabel jLabel_x1y2;
    private javax.swing.JLabel jLabel_x1y3;
    private javax.swing.JLabel jLabel_x2y1;
    private javax.swing.JLabel jLabel_x2y2;
    private javax.swing.JLabel jLabel_x2y3;
    private javax.swing.JLabel jLabel_x3y1;
    private javax.swing.JLabel jLabel_x3y2;
    private javax.swing.JLabel jLabel_x3y3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemConnect;
    private javax.swing.JMenuItem jMenuItemCreate;
    private javax.swing.JMenuItem jMenuItemQuit;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelBank;
    private javax.swing.JPanel jPanelField;
    private javax.swing.JPanel jPanel_x1y2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextAreaChat;
    private javax.swing.JTextArea jTextAreaSystem;
    private javax.swing.JTextField jTextFieldChat;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent e) {
    }

    @Override
    public void keyReleased(KeyEvent e) {
    }

    private void enableChat(boolean enable) {
        jTextFieldChat.setEnabled(enable);
    }

    public void enableField(boolean enable) {
        if (enable) {
            jButton_x1y1.setEnabled(true);
            jButton_x1y2.setEnabled(true);
            jButton_x1y3.setEnabled(true);
            jButton_x2y1.setEnabled(true);
            jButton_x2y2.setEnabled(true);
            jButton_x2y3.setEnabled(true);
            jButton_x3y1.setEnabled(true);
            jButton_x3y2.setEnabled(true);
            jButton_x3y3.setEnabled(true);
            jLabelBank1.setEnabled(true);
            jLabelBank2.setEnabled(true);
            jLabelBank3.setEnabled(true);
            jButtonDone.setEnabled(true);
        } else {
            jButton_x1y1.setEnabled(false);
            jButton_x1y2.setEnabled(false);
            jButton_x1y3.setEnabled(false);
            jButton_x2y1.setEnabled(false);
            jButton_x2y2.setEnabled(false);
            jButton_x2y3.setEnabled(false);
            jButton_x3y1.setEnabled(false);
            jButton_x3y2.setEnabled(false);
            jButton_x3y3.setEnabled(false);
            jLabelBank1.setEnabled(false);
            jLabelBank2.setEnabled(false);
            jLabelBank3.setEnabled(false);
            jButtonDone.setEnabled(false);
        }

    }

    public void updateField() {
        //This method updates the playing field according to the settings in the logic variables
        //The tokens that belong to th opponent are disabled 
        //Bank
        if (logic.getBank() > 0) {
            jLabelBank1.setIcon(sPlayerIcon);
            if (logic.getBank() > 1) {
                jLabelBank2.setIcon(sPlayerIcon);
                if (logic.getBank() > 2) {
                    jLabelBank3.setIcon(sPlayerIcon);
                }
            }
        }
        //X1Y1
        if (logic.getX1y1() == 0 || logic.getX1y1() == logic.getPlayer()) {
            jButton_x1y1.setEnabled(true);
            if (logic.getX1y1() == logic.getPlayer()) {
                jButton_x1y1.setIcon(playerIcon);
            }
        } else {
            jButton_x1y1.setEnabled(false);
            jButton_x1y1.setIcon(opponentIcon);
        }
        //X1Y2
        if (logic.getX1y2() == 0 || logic.getX1y2() == logic.getPlayer()) {
            jButton_x1y2.setEnabled(true);
            if (logic.getX1y2() == logic.getPlayer()) {
                jButton_x1y2.setIcon(playerIcon);
            }
        } else {
            jButton_x1y2.setEnabled(false);
            jButton_x1y2.setIcon(opponentIcon);
        }
        //X1Y3
        if (logic.getX1y3() == 0 || logic.getX1y3() == logic.getPlayer()) {
            jButton_x1y3.setEnabled(true);
            if (logic.getX1y3() == logic.getPlayer()) {
                jButton_x1y3.setIcon(playerIcon);
            }
        } else {
            jButton_x1y3.setEnabled(false);
            jButton_x1y3.setIcon(opponentIcon);
        }
        //X2Y1
        if (logic.getX2y1() == 0 || logic.getX2y1() == logic.getPlayer()) {
            jButton_x2y1.setEnabled(true);
            if (logic.getX2y1() == logic.getPlayer()) {
                jButton_x2y1.setIcon(playerIcon);
            }
        } else {
            jButton_x2y1.setEnabled(false);
            jButton_x2y1.setIcon(opponentIcon);
        }
        //X2Y2
        if (logic.getX2y2() == 0 || logic.getX2y2() == logic.getPlayer()) {
            jButton_x2y2.setEnabled(true);
            if (logic.getX2y2() == logic.getPlayer()) {
                jButton_x2y2.setIcon(playerIcon);
            }
        } else {
            jButton_x2y2.setEnabled(false);
            jButton_x2y2.setIcon(opponentIcon);
        }
        //X2Y3
        if (logic.getX2y3() == 0 || logic.getX2y3() == logic.getPlayer()) {
            jButton_x2y3.setEnabled(true);
            if (logic.getX2y3() == logic.getPlayer()) {
                jButton_x2y3.setIcon(playerIcon);
            }
        } else {
            jButton_x2y3.setEnabled(false);
            jButton_x2y3.setIcon(opponentIcon);
        }
        //X3Y1
        if (logic.getX3y1() == 0 || logic.getX3y1() == logic.getPlayer()) {
            jButton_x3y1.setEnabled(true);
            if (logic.getX3y1() == logic.getPlayer()) {
                jButton_x3y1.setIcon(playerIcon);
            }
        } else {
            jButton_x3y1.setEnabled(false);
            jButton_x3y1.setIcon(opponentIcon);
        }
        //X3Y2
        if (logic.getX3y2() == 0 || logic.getX3y2() == logic.getPlayer()) {
            jButton_x3y2.setEnabled(true);
            if (logic.getX3y2() == logic.getPlayer()) {
                jButton_x3y2.setIcon(playerIcon);
            }
        } else {
            jButton_x3y2.setEnabled(false);
            jButton_x3y2.setIcon(opponentIcon);
        }
        //X3Y3
        if (logic.getX3y3() == 0 || logic.getX3y3() == logic.getPlayer()) {
            jButton_x3y3.setEnabled(true);
            if (logic.getX3y3() == logic.getPlayer()) {
                jButton_x3y3.setIcon(playerIcon);
            }
        } else {
            jButton_x3y3.setEnabled(false);
            jButton_x3y3.setIcon(opponentIcon);
        }
    }
}
